### ISSUE TITLE
The `movement` and `minimal` examples don't compile

### ISSUE THREAD

**Issue by stevenliebregt** [zaycev/bevy-magic-light-2d#14]
I'm guessing the long error about the `trait bound for blabla` is caused by MainCamera not being there.

![image](https://user-images.githubusercontent.com/17197587/217063472-69b43dec-b2f7-479d-ab8a-f8ae760b3b8c.png)

**Comment by BrettWitty** [comment]
I get the same problems for `minimal` and `movement`, but mostly around `.handle` not existing. I only get the camera issue for `movement`.

**Comment by zaycev** [comment]
I accidentally broke them after adding 3 cameras setup in one of the last PRs. I can try to send a fix over the weekend.

**Comment by zaycev** [comment]
Fixed in #19
