### ISSUE TITLE
Cannot run `krypta` example on Linux

### ISSUE THREAD

**Issue by BrettWitty** [zaycev/bevy-magic-light-2d#15]
In running `cargo run --example krypta`, I get
```sh
thread 'main' panicked at 'Failed to initialize any backend! Wayland status: NoCompositorListening X11 status: "backend disabled"', /home/brettw/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.5/src/platform_impl/linux/mod.rs:719:9
```

**Comment by dbenson24** [comment]
That would not be related to this crate. It looks like you are running this over ssh. Run it locally

**Comment by BrettWitty** [comment]
I did the following in a local terminal:
- `git clone https://github.com/zaycev/bevy-magic-light-2d.git`
- `cd bevy-magic-light-2d`
- `cargo run --example krypta`

I got the above error. My distro:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal
````

I assume the `Cargo.toml` disabling all bevy default features and requiring `wayland` might not work if I'm on X11 (as double-checked by `XDG_SESSION_TYPE`.

**Comment by dbenson24** [comment]
Can you run other examples from the Bevy repo?

**Comment by BrettWitty** [comment]
No, unfortunately, as per #14.

**Comment by dbenson24** [comment]
No I meant the actual Bevy repo, not bevy magic light. Have you successfully run any Bevy app before

**Comment by BrettWitty** [comment]
Yes, I have. I just pulled the latest bevy main, and ran examples from that.

On `bevy-magic-light-2d` I did `cargo add bevy --features x11` which adds the `x11` feature back in and the `krypta` example compiles and runs. Disabling all default features and defaulting just to `wayland` is the issue for some Linux setups.
