### ISSUE TITLE
Possible missing bevy feature in Cargo.toml

### ISSUE THREAD

**Issue by 39george** [zaycev/bevy-magic-light-2d#24]
Thanks for the update! I noticed that it won't compile in my project without `bevy_pbr` feature enabled in Cargo.toml:
```
2 | use bevy::pbr::{MAX_CASCADES_PER_LIGHT, MAX_DIRECTIONAL_LIGHTS};
  |           ^^^ could not find `pbr` in `bevy`
```
It is strange, because `krypta` example working without any issues..

and if someone uses bevy/dynamic_linking, `crate-type = ["cdylib", "lib", "staticlib"]` line in Cargo.toml causes this:

```
error: crate `bevy_dylib` required to be available in rlib format, but was not found in this form
```

**Comment by zaycev** [comment]
Thanks for reporting this. Seems like a small change, I will try to send a fix this week.

**Comment by zaycev** [comment]
Seems like #29 fixed it.
