### ISSUE TITLE
PR#28 breaks rendering on 3080Ti

### ISSUE THREAD

**Issue by 00alia00** [zaycev/bevy-magic-light-2d#30]
Looks like PR#28 causes rendering to break on my laptop

![krypta_AhEssZfTKa](https://github.com/zaycev/bevy-magic-light-2d/assets/537506/2e6d24a4-aa8f-4ecf-a38a-6bced7a7a4ab)

```
AdapterInfo { name: "NVIDIA GeForce RTX 3080 Ti Laptop GPU", vendor: 4318, device: 9248, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "517.40", backend: Vulkan }
SystemInfo { os: "Windows 11 Pro", kernel: "22621", cpu: "12th Gen Intel(R) Core(TM) i9-12900H", core_count: "14", memory: "31.7 GiB" }
```

**Comment by zaycev** [comment]
Will try to take a look this week. Likely I have the same GPU :)

**Comment by amytimed** [comment]
any update?

**Comment by 0xD21F** [comment]
I can confirm the same issue, 3080Ti also.

```
AdapterInfo { name: "NVIDIA GeForce RTX 3080 Ti", vendor: 4318, device: 8712, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "516.94", backend: Vulkan }
SystemInfo { os: "Windows 11 Pro", kernel: "22000", cpu: "AMD Ryzen 9 5900X 12-Core Processor", core_count: "12", memory: "63.9 GiB" }
```

If I roll back PR#28, it begins to work again.

**Comment by awski** [comment]
Not sure if that's helpful, but it also doesn't work on 2070S

`AdapterInfo { name: "NVIDIA GeForce RTX 2070 SUPER", vendor: 4318, device: 7812, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "545.84", backend: Vulkan }
SystemInfo { os: "Windows 11 Pro", kernel: "22621", cpu: "AMD Ryzen 7 2700X Eight-Core Processor", core_count: "8", memory: "32.0 GiB" }`

**Comment by zaycev** [comment]
Should be fixed on main. Compositing pass which blends multiple layers was broken when we accidentally changed clear color to black instead of transparent in krypta example.

**Comment by zaycev** [comment]
Closing now. @aMySour, @0xD21F,  @awski, @00alia00 Lmk if you still see problems.
