### ISSUE TITLE
Release to cargo

### ISSUE THREAD

**Issue by zaycev** [zaycev/bevy-magic-light-2d#38]

**Comment by ryanpeach** [comment]
Are you still planning to do this?

**Comment by ryanzec** [comment]
Is there any update on this as it would make it much easier to integrate into an existing project as a crate?

**Comment by LeviLovie** [comment]
Could you please do that? It is too complicated to add your library in.

**Comment by tigerplush** [comment]
v0.8 update to support bevy v0.14.1 is planned for this week.
It will entail the release of a crate

**Comment by tigerplush** [comment]
magic light is now available on crates as of 0.8
