### ISSUE TITLE
You are moving the world instead of moving the Camera

### ISSUE THREAD

**Issue by ryanpeach** [zaycev/bevy-magic-light-2d#51]
This will really mess up a lot of standard bevy practices.

**Comment by zaycev** [comment]
> This will really mess up a lot of standard bevy practices.

Sorry, I don't really get what do you mean. Can you please give an example where do you see this in code ?

**Comment by tigerplush** [comment]
I'm going to closed this issue for 3 reasons:
a) there hasn't been an update since Feb 19
b) We're spawning the PostProcessingCamera with the PostProcessQuad attached (which is what luan achieved in their PR) and
c) When running the krypta example, the Postprocessingcamera will not be moved
