### ISSUE TITLE
Huge FPS difference between magic light on bevy 0.13 vs 0.14.1

### ISSUE THREAD

**Issue by CarsonBurke** [zaycev/bevy-magic-light-2d#65]
All else being equal, I'm seeing significant differences in my benchmarks with bevy 0.13 vs 0.14. In my benchmarks, with marginal differences in implementation between 0.13 and 0.14.1, my FPS goes from 165-80 (depending on zoom) on 0.13 to around 40 (irregardless of zoom) on 0.14.1. This seems partly to be regressions in 0.14.1 (as I've told, to allow to future greater optimizations in future bevy versions), but due to the magnitude of difference it appears that something changed with 0.14.1 that is having an exceptional impact in regards to magic light's performance.

**Comment by tigerplush** [comment]
Accidentally the frustrum culling was disabled in our efforts to update to bevy 0.14. I've reenabled the frustrum culling in #68 and we should be back on the previous performance
