### ISSUE TITLE
update tilemap example

### ISSUE THREAD

**Issue by uzunenx** [zaycev/bevy-magic-light-2d#70]
tried porting the tilemap example in [zaycev/tilemap](https://github.com/zaycev/bevy-magic-light-2d/tree/zaycev/tilemap) to 0.14 but the skylight does not seem to work after #68 was merged.

**Comment by tigerplush** [comment]
hey @uzunenx , could you provide a litte more context? Code, screenshots etc? because in the krypta example the skylight still works

![image](https://github.com/user-attachments/assets/21cf97f9-6d27-49e2-b3f7-3e94d7412e2b)
this is it with intensity 2.5

**Comment by uzunenx** [comment]
my mistake, the tilemap example works fine after retesting. im guessing that this was an error that #68 fixed in my own project that is based off the example.

before
the skylight creates a small zone that gets smaller at negative intensitys and syncs with the rest of the map at higher intensity
![image2](https://github.com/user-attachments/assets/c9009bb6-c2f6-43ae-9697-bf278075e043)
after
the skylight is in sync with the whole map
![image](https://github.com/user-attachments/assets/9356f8c2-a24f-41ad-bacd-8bb3805acab8)
